# Generated by Django 4.0.5 on 2022-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_producer_product_amount_product_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
